version: '3.9'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=votingmanager
      - POSTGRES_USER=votingmanager
      - POSTGRES_DB=votingmanager
    ports:
      - "5432:5432"